version: '3.8'

services:
  db:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_DB: medichat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring_net
  app:
    build: .
    container_name: my_spring_app
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod # Docker 실행 시 prod db로 연결 변경
    ports:
      - "8080:8080"
    networks:
      - spring_net
volumes:
  postgres_data:

networks:
  spring_net: